#!/bin/bash
trap_help

# Globals
export MOD_PATH=`dirname $0`
export MOD_NAME=landscape
export MOD_BASE_TEMPLATE=landscape.yaml.template
export MOD_SSL_STATE_DIR=${MOD_NAME}
[ -n "${MASTER_OPTS[BUNDLE_NAME]}" ] && \
    MOD_SSL_STATE_DIR="${MOD_SSL_STATE_DIR}-${MASTER_OPTS[BUNDLE_NAME]}"

# opts that 02configure does not recognise that get passed to the generator
export -a MOD_PASSTHROUGH_OPTS=()

# Collection of messages to display at the end
export -a MOD_MSGS=()

# Array list of overlays to use with this deployment.
export -a MOD_OVERLAYS=()

export -A MOD_PARAMS=()

# Series & Release Info
declare -A lts=( [xenial]=landscape
                 [bionic]=landscape )
declare -A nonlts=( [disco]=landscape
                    [eoan]=landscape )
