#!/bin/bash
# NOTE: global variables must be first defined in 01setup

MOD_PARAMS[__LANDSCAPE_VERSION__]="19.01"

# Skip processing input if it includes exclusive passthrough options
! has_excl_passthrough_opt && \
while (($# > 0))
do
    case "$1" in
        --landscape-version)  #__OPT__type:<int>
            MOD_PARAMS[__LANDSCAPE_VERSION__]=$2
            shift
            ;;
        --ha)
            MOD_OVERLAYS+=( "landscape-ha.yaml" )
            ;;
        *)
            echo "ERROR: invalid input '$1'"
            _usage
            exit 1
            ;;
    esac
    shift
done

target=$series
[ -z "$pocket" ] || target=${target}-$pocket
MOD_PASSTHROUGH_OPTS+=( --release-name $target )

print_msgs
