#!/bin/bash
LIB_COMMON=`dirname $0`/common
. $LIB_COMMON/helpers

trap_help

#cleanup () { :; }
#trap cleanup EXIT

# Globals
export MOD_PATH=`dirname $0`
export MOD_BASE_TEMPLATE=ceph.yaml.template

# opts that 02configure does not recognise that get passed to the generator
export -a MOD_UNKNOWN_OPTS=()

# Collection of messages to display at the end
export -a MOD_MSGS=()

# Array list of overlays to use with this deployment.
export -a MOD_OVERLAYS=()

export -A MOD_PARAMS=()

# Series & Release Info (see http://docs.ceph.com/docs/master/releases/)
export -A APP_RELEASE_NAMES=( [firefly]=icehouse
                              [jewel]=mitaka
                              [luminous]=pike
                              [mimic]=rocky
                              [nautilus]=train )
