#!/bin/bash

# Renderers defined here must be applied to any/all templates that contain Juju resources stanzas.

render_resources_path () {
    local file="$1"
    local name=`basename $file`
    local path=resources/${name%%.*}/

    sed -i -r "s,__RESOURCES_PATH__,$path,g" $file
}

