#!/bin/bash
# Global variables are first defined in 00setup and module
# dependencies are defined in 01import-config-defaults
#
# All overlay/bundle variables (MOD_PARAMS) defaults must go into
# the <module>/module_defaults file.


if [ $# -eq 0 ]; then
    echo "ERROR: required input: --k8s-model"
    exit 1
fi

MOD_PARAMS[__JUJU_CA_CERT__]=`juju controller-config --format json| \
                                  jq -r '.["ca-cert"]' 2>/dev/null|
                                  base64 -w 0`
[ -n "${MOD_PARAMS[__JUJU_CA_CERT__]}" ] || \
    { echo "ERROR: unable to get controller ca-cert"; exit 1; }

while (($# > 0))
do
    case $1 in
        --k8s-model) #__OPT__type:<str>
            MOD_PARAMS[__K8S_MODEL__]=$2
            MOD_PARAMS[__JUJU_SSHKEY__]=`juju ssh-keys -m $2 --full | grep ssh-rsa` || echo "ERROR: unable to get Juju ssh keys from model $2"
            [ -n "${MOD_PARAMS[__JUJU_SSHKEY__]}" ] || exit 1
            shift
            ;;
        *)
            echo "ERROR: invalid input '$1'"
            _usage
            exit 1
            ;;
    esac
    shift
done

