#!/bin/bash -ex

# prodstack6 overrides
[[ -z "$NAMESERVER" ]] && export NAMESERVER="91.189.91.131"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.140.56.22"

# Set defaults, if not already set.
[[ -z "$GATEWAY" ]] && export GATEWAY="10.142.35.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.142.35.0/24"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.142.35.200:10.142.35.254"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"

export UNDERCLOUD_NETWORK_NAME="$(sed -E --quiet "s/.+OS_PROJECT_NAME=(.+)_project/net_\1/p" ~/novarc)"

./profiles/default "$@"
