#!/bin/bash -ex
source ~/novarc
export GATEWAY=`openstack subnet show subnet_${OS_USERNAME}-psd-internal -c gateway_ip -f value`
CIDR=`openstack subnet show subnet_${OS_USERNAME}-psd-internal -c cidr -f value`
ABC=${CIDR%.0*}

[[ -z "$NAMESERVER" ]] && export NAMESERVER="91.189.91.131"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.140.56.22"

# Set defaults, if not already set.
[[ -z "$GATEWAY" ]] && export GATEWAY="$GATEWAY"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="$CIDR"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="${ABC}.3:${ABC}.254"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"

export UNDERCLOUD_NETWORK_NAME="$(sed -E --quiet "s/.+OS_PROJECT_NAME=(.+)_project/net_\1-psd-internal/p" ~/novarc)"

./profiles/default "$@"
