#!/bin/bash -ex

# serverstack overrides
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.245.160.2"
[[ -z "$SWIFT_URI" ]] && export SWIFT_URI="http://10.245.161.162"

export UNDERCLOUD_NETWORK_NAME="$(sed -E --quiet "s/.+OS_PROJECT_NAME=(.+)/\1_admin_net/p" ~/novarc)"

./profiles/default "$@"
