#!/bin/bash -ex
source ~/novarc
# stsstack overrides
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.230.64.2"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.230.19.58"

export UNDERCLOUD_EXT_NET="${OS_USERNAME}_admin_net"

./profiles/default "$@"
