#!/bin/bash

# Globals
export MOD_NAME=openstack
export MOD_BASE_TEMPLATE=openstack.yaml.template
export MOD_SSL_STATE_DIR=${MOD_NAME}
[ -n "${MASTER_OPTS[BUNDLE_NAME]}" ] && \
    MOD_SSL_STATE_DIR="${MOD_SSL_STATE_DIR}-${MASTER_OPTS[BUNDLE_NAME]}"

# opts that 02configure does not recognise that get passed to the generator
export -a MOD_PASSTHROUGH_OPTS=()

# Collection of messages to display at the end
export -A MOD_MSGS=()
# Use order 0 to ensure this is first displayed
MOD_MSGS[0_common.0]="run ./configure to initialise your deployment"
MOD_MSGS[0_common.1]="source novarc"
MOD_MSGS[0_common.2]="add rules to default security group: ./tools/sec_groups.sh"

# Array list of overlays to use with this deployment.
export -a MOD_OVERLAYS=()

export -A MOD_PARAMS=()
# override this for openstack
MASTER_OPTS[CHARM_TRACK]=$release/
MASTER_OPTS[CHARM_CEPH_TRACK]=`get_app_release_name $release`/
if [[ $series = bionic ]]; then
    MASTER_OPTS[CHARM_RABBIT_TRACK]=3.6/
elif [[ $series = focal ]]; then
    MASTER_OPTS[CHARM_RABBIT_TRACK]=3.8/
else
    MASTER_OPTS[CHARM_RABBIT_TRACK]=latest/
fi
