#!/bin/bash

# Globals
export MOD_NAME=openstack
export MOD_BASE_TEMPLATE=openstack.yaml.template
export MOD_SSL_STATE_DIR=${MOD_NAME}
[ -n "${MASTER_OPTS[BUNDLE_NAME]}" ] && \
    MOD_SSL_STATE_DIR="${MOD_SSL_STATE_DIR}-${MASTER_OPTS[BUNDLE_NAME]}"

# opts that 02configure does not recognise that get passed to the generator
export -a MOD_PASSTHROUGH_OPTS=()

# Collection of messages to display at the end
export -A MOD_MSGS=()
# Use order 0 to ensure this is first displayed
# NOTE: start at offset 10 to allow for actions to be added before.
MOD_MSGS[0_common.10]="run ./configure to initialise your deployment"
MOD_MSGS[0_common.11]="source novarc"
MOD_MSGS[0_common.12]="add rules to default security group: ./tools/sec_groups.sh"

# Array list of overlays to use with this deployment.
export -a MOD_OVERLAYS=()

export -A MOD_PARAMS=()
