#!/bin/bash
export INTERNAL_BUNDLE_CONFIG_RENDERER=
export INTERNAL_BUNDLE_CONFIG=
if ((${#MOD_PARAMS[@]})); then
    export INTERNAL_BUNDLE_CONFIG_RENDERER=`mktemp`
    export INTERNAL_BUNDLE_CONFIG=`mktemp`
    echo -n "sed -i " > $INTERNAL_BUNDLE_CONFIG_RENDERER
    for p in ${!MOD_PARAMS[@]}; do
        echo -n "-e 's,$p,${MOD_PARAMS[$p]},g' " >> $INTERNAL_BUNDLE_CONFIG_RENDERER
        echo "${p}: \"${MOD_PARAMS[$p]}\"" >> $INTERNAL_BUNDLE_CONFIG
    done
fi

. $MOD_DIR/common/generate_bundle_base

for f in $INTERNAL_BUNDLE_CONFIG_RENDERER $INTERNAL_BUNDLE_CONFIG; do
    [ -n "$f" ] && [ -r "$f" ] && rm -f $f
done
