#!/bin/bash
# Global variables are first defined in 00setup and module
# dependencies are defined in 01import-config-defaults
#
# All overlay/bundle variables (MOD_PARAMS) defaults must go into
# the <module>/module_defaults file.

if ! `juju --version| egrep -q "^3.2"`; then
    echo "ERROR: juju version 3.2 or above is required for deploying JAAS"
    exit 1
fi

if ! `snap list| grep -q candid`; then
    sudo snap install candid --channel latest/candidate    
fi

candid_keys=$(pwd)/keys
mkdir -p $candid_keys
/snap/candid/current/bin/bakery-keygen > ${candid_keys}/bakery-key.json
cat ${candid_keys}/bakery-key.json | jq -r .public | tr -d '\n' > ${candid_keys}/public-key
cat ${candid_keys}/bakery-key.json | jq -r .private | tr -d '\n' > ${candid_keys}/private-key
CANDID_URL=https://candid.sts candid create-agent --admin   -f ${candid_keys}/admin.agent
cat ${candid_keys}/admin.agent | jq -r .key.public | tr -d '\n' > ${candid_keys}/admin-agent-public-key

MOD_PARAMS[__CANDID_PUB_KEY__]=`cat $candid_keys/public-key`
MOD_PARAMS[__CANDID_PRIV_KEY__]=`cat $candid_keys/private-key`
MOD_PARAMS[__CANDID_ADMIN_AGENT_KEY__]=`cat $candid_keys/admin-agent-public-key`

# Skip processing input if it includes exclusive passthrough options
! has_excl_passthrough_opt && \
while (($# > 0))
do
    case "$1" in
        *)
            echo "ERROR: invalid input '$1'"
            _usage
            exit 1
            ;;
    esac
    shift
done

