applications:
  containerd:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__containerd
    options:
      http_proxy: __CONTAINERD_PROXY__
      https_proxy: __CONTAINERD_PROXY__
      no_proxy: __CONTAINERD_NO_PROXY__
relations:
 - [ 'containerd:containerd', '__K8S_WORKER_CHARM__:container-runtime' ]
 - [ 'containerd:containerd', '__K8S_CONTROLLER_CHARM__:container-runtime' ]
