applications:
  e2e:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__kubernetes-e2e
    num_units: 1
relations:
  - [ 'e2e:kube-control', '__K8S_CONTROLLER_CHARM__:kube-control' ]
  - [ 'e2e:__K8S_CONTROLLER_CHARM__', '__K8S_CONTROLLER_CHARM__:kube-api-endpoint' ]
