applications:
  __K8S_CONTROLLER_CHARM__:
    options:
      ha-cluster-vip: __VIP__
  __K8S_CONTROLLER_CHARM__-hacluster:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__hacluster
    options:
      cluster_count: __NUM_K8S_CONTROL_PLANE_UNITS__
relations:
  - [ __K8S_CONTROLLER_CHARM__-hacluster, __K8S_CONTROLLER_CHARM__ ]
