applications:
  flannel:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__flannel
relations:
  - [ 'flannel:cni', '__K8S_CONTROLLER_CHARM__:cni' ]
  - [ 'flannel:cni', '__K8S_WORKER_CHARM__:cni' ]
  - [ 'flannel:etcd', 'etcd:db' ]
