# See https://ubuntu.com/kubernetes/docs/keepalived

applications:
  kubeapi-lb-keepalived:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__keepalived
    options:
      virtual_ip: __VIP__
      vip_hostname: __VIP__
  kubeapi-load-balancer:
    options:
      extra_sans: __VIP__
  __K8S_CONTROLLER_CHARM__:
    options:
      extra_sans: __VIP__
relations:
  - [ kubeapi-lb-keepalived:juju-info, kubeapi-load-balancer:juju-info ]
  - [ kubeapi-lb-keepalived:lb-sink, kubeapi-load-balancer:website ]
  - [ kubeapi-lb-keepalived:loadbalancer, __K8S_CONTROLLER_CHARM__:loadbalancer ]
  - [ kubeapi-lb-keepalived:website, __K8S_WORKER_CHARM__:kube-api-endpoint ]

