applications:
  canal:
    charm: __CHARM_STORE____CHARM_CS_NS____CHARM_CH_PREFIX__canal
relations:
  - [ 'canal:cni', '__K8S_CONTROLLER_CHARM__:cni' ]
  - [ 'canal:cni', '__K8S_WORKER_CHARM__:cni' ]
  - [ 'canal:etcd', 'etcd:db' ]
