relations:
  - [__K8S_CONTROLLER_CHARM__:juju-info, telegraf:juju-info]
  - [__K8S_WORKER_CHARM__:juju-info, telegraf:juju-info]
  - [__K8S_CONTROLLER_CHARM__:prometheus, prometheus:manual-jobs]
  - [__K8S_CONTROLLER_CHARM__:grafana, grafana:dashboards]
  - [etcd:juju-info, telegraf:juju-info]
