#!/bin/bash

set -ex

. ./profiles/common

install_packages

# Set sts-stack overrides, if not already set.
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.230.64.2"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.230.19.58"

# Set serverstack defaults, if not already set.
[[ -z "$GATEWAY" ]] && export GATEWAY="10.5.0.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.5.0.0/16"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.5.150.0:10.5.200.254"
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.245.168.6"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.245.161.162"

# Accept network type as first parameter, assume gre if unspecified
net_type=${1:-"gre"}

# If not on bare metal, add extra port to overcloud neutron-gateway and configure charm to use it
if [[ "${BARE_METAL^^}" != "TRUE" ]]; then
    source ~/novarc
    ./bin/post-deploy-config neutron-gateway
fi

# Configure neutron networking on overcloud
source novarc
./bin/neutron-ext-net-ksv3 --project admin --network-type flat -g $GATEWAY -c $CIDR_EXT -f $FIP_RANGE ext_net
./bin/neutron-tenant-net-ksv3 --project admin --network-type $net_type -r provider-router -N $NAMESERVER private $CIDR_PRIV
ext_net=$(openstack network list --name ext_net -f value -c ID)

# Create demo/testing users, tenants and flavor
create_tempest_users_v3

# Download images if not already present
mkdir -vp ~/images
#upload_image cloudimages trusty trusty-server-cloudimg-amd64-disk1.img
upload_image cloudimages xenial xenial-server-cloudimg-amd64-disk1.img
upload_image cloudimages bionic bionic-server-cloudimg-amd64.img
upload_image swift cirros cirros-0.4.0-x86_64-disk.img
upload_image swift cirros2 cirros-0.3.5-x86_64-disk.img
image_id=$(openstack image list --name cirros -f value -c ID)
image_alt_id=$(openstack image list --name cirros_alt -f value -c ID)

echo "Flavors"
create_tempest_flavors
create_default_flavors

echo "Tempest"
router=$(openstack router list --name provider-router -f value -c ID)
# Gather vars for tempest template
keystone=$(juju run --unit keystone/0 unit-get private-address)
dashboard=$(juju run --unit openstack-dashboard/0 unit-get private-address)
ncc=$(juju run --unit nova-cloud-controller/0 unit-get private-address)
http=${OS_AUTH_PROTOCOL:-http}
default_domain_id=$(openstack domain list | awk '/default/ {print $2}')

# Insert vars into tempest conf
sed -e "s/__IMAGE_ID__/$image_id/g" -e "s/__IMAGE_ALT_ID__/$image_alt_id/g" \
    -e "s/__DASHBOARD__/$dashboard/g" -e "s/__KEYSTONE__/$keystone/g" \
    -e "s/__EXT_NET__/$ext_net/g" -e "s/__PROTO__/$http/g" \
    -e "s/__SWIFT__/$SWIFT_IP/g" \
    -e "s/__NAMESERVER__/$NAMESERVER/g" \
    -e "s/__CIDR_PRIV__/${CIDR_PRIV////\\/}/g" \
    -e "s/__NCC__/$ncc/g" \
    -e "s/__DEFAULT_DOMAIN_ID__/$default_domain_id/g" \
    templates/tempest/tempest-v3.conf.template > tempest.conf

# Git tempest, place the rendered tempest template
[ -d tempest ] || git clone https://github.com/openstack/tempest
git --git-dir=tempest/.git --work-tree=tempest checkout master
git --git-dir=tempest/.git --work-tree=tempest pull
cp tempest.conf tempest/etc
cp templates/tempest/accounts.yaml tempest/etc
