#!/bin/bash
#
# PLEASE AVOID PUTTING BUNDLE-SPECIFIC CODE IN HERE. INSTEAD USE THE INDIVIDUAL
# BUNDLE GENERATORS.
#
declare -A overlays_deduped=()
declare -a overlay_opts=()
charm_channel=
bundle_name=
replay=false
run_command=false
list_bundles=false
create_model=false
use_stable_charms=false
model_config=


while (($# > 0))
do
    case "$1" in
        --charm-channel)
            charm_channel=$2
            shift
            ;;
        --create-model)
            # creates a model using the value provided by --name
            create_model=true
            ;;
        --defaults)
            # boolean stub (see usage for explanation)
            ;;
        --model-config)
            if [ -z "$model_config" ]; then
                model_config="$2"
            else
                model_config+=" $2"
            fi
            shift
            ;;
        --series|-s)
            # stub - see get_series
            shift
            ;;
        --release|-r)
            # stub - see get_release
            shift
            ;;
        --pocket|-p)
            # archive pocket e.g. proposed
            # stub - see get_pocket
            shift
            ;;
        --name|-n)
            # give bundle set a name and store under named dir
            bundle_name=$2
            shift
            ;;
        --replay)
            # replay the last recorded command if exists
            replay=true
            ;;
        --list)
            list_bundles=true
            ;;
        --list-overlays)
            list_overlays
            exit
            ;;
        --run)
            # deploy bundle once generated
            run_command=true
            ;;
        --use-stable-charms)
            use_stable_charms=true
            ;;
        -h|--help)
            _usage
            exit 0
            ;;
        *)
            echo "ERROR: invalid input '$1'"
            _usage
            exit 1
            ;;
    esac
    shift
done

if [ -z "$MOD_BASE_TEMPLATE" ]; then
    echo "ERROR: no template provided with --template"
    exit 1
elif [ -z "$MOD_PATH" ]; then
    echo "ERROR: no module name provided"
    exit 1
elif $create_model && [ -z "$bundle_name" ]; then
    echo "ERROR: no --name provided so cannot create Juju model" 
    exit 1
fi

if $create_model; then
    if `juju list-models| egrep -q "^$bundle_name\* "`; then
        echo -e "Juju model '$bundle_name' already exists and is the current context - skipping create\n"
    elif `juju list-models| egrep -q "^$bundle_name "`; then
        echo "Juju model '$bundle_name' already exists but is not the current context - switching context"
        juju switch $bundle_name
        echo ""
    else
        echo "Creating Juju model $bundle_name"
        juju add-model $bundle_name
        echo ""
    fi
fi
[ -n "$model_config" ] && juju model-config $model_config

bundles_dir=`get_bundle_state_dir`

if $list_bundles; then
    state_root=`get_bundle_state_root`
    if [ -d "$state_root" ]; then
        echo -e "Existing bundles:\n./b (default)"
        find $state_root/* -maxdepth 0 -type d| egrep -v "/o$|resources" 
        echo ""
    else
        echo "There are currently no bundles."
    fi
    exit
fi
mkdir -p $bundles_dir

finish ()
{
    if $replay; then
        target=${bundles_dir}/command
        echo -e "INFO: replaying last known command (from $target)\n"
        [ -e "$target" ] || { echo "ERROR: $target does not exist"; exit 1; }
    fi
    echo "Command to deploy:"
    cat ${bundles_dir}/command
    if $run_command; then
        . ${bundles_dir}/command
    fi
    $replay && exit 0 || true
}

# Replay ignores any input args and just prints the previously generated
# command.
$replay && finish

# Each custom bundle generator can specify a set of parameters to apply to
# bundle templates as variables. They are converted into a sed statement that
# is passed in to here inside a file and run against the template(s). There is
# therefore no need to add parameters to this function and they should only
# be defined in the custom generators.
render () {
    # generic parameters only
    sed -i "s,__SERIES__,$series,g" $1

    # service-specific replacements
    if [ -n "$INTERNAL_BUNDLE_CONFIG_RENDERER" ]; then
        eval `cat $INTERNAL_BUNDLE_CONFIG_RENDERER` $1
    fi

    if $use_stable_charms; then
        sed -i -r 's,~openstack-charmers-next/,,g' $1
    fi
}

render_resources_path () {
    file="$1"
    name=`basename $file`
    path=resources/${name%%.*}/

    sed -i -r "s,__RESOURCES_PATH__,$path,g" $file
}

target=${series}-$release
[ -z "$pocket" ] || target=${target}-$pocket

if $use_stable_charms; then
    msg="using stable charms"
else
    msg="using dev/next charms"
fi

channel_param=
if [ -n "$charm_channel" ]; then
    channel_param="--channel=$charm_channel"
fi

app_release_name=`get_app_release_name "$release"`
[ -n "$app_release_name" ] && app_release_name="($app_release_name) "

# Make copy of base template, render, and store in named dir.
dtmp=`mktemp -d`
template_path=$dtmp/`basename $MOD_BASE_TEMPLATE`
bundle=${template_path%%.template}
cp $MOD_BASE_TEMPLATE $bundle
render $bundle
mv $bundle $bundles_dir
[ -r "$INTERNAL_BUNDLE_CONFIG" ] && \
    cp $INTERNAL_BUNDLE_CONFIG $bundles_dir/config
rmdir $dtmp

# Copy base bundle resources to bundles dir (if exists)
resource_path=$MOD_PATH/resources/
if [ -d "$resource_path" ]; then
    mkdir -p $bundles_dir/resources
    name=`basename $bundle`
    if [ -d "$resource_path/${name%%.yaml}" ]; then
        cp -r $resource_path/${name%%.yaml} $bundles_dir/resources
        # add absolute path for resources
        render_resources_path $bundles_dir/$name
    fi
fi
# De-duplicate overlay list and create bundle structure.
if ((${#MOD_OVERLAYS[@]})); then
    mkdir -p $bundles_dir/o
    declare -a msgs=()
    for overlay in ${MOD_OVERLAYS[@]}; do
        [ "${overlays_deduped[$overlay]:-null}" = "null" ] || continue
        cp overlays/$overlay $bundles_dir/o
        ((${#overlay_opts[@]}==0)) && overlay_opts+=("")  # left padding
        overlay_opts+=( --overlay $bundles_dir/o/$overlay )
        render $bundles_dir/o/$overlay
        overlays_deduped[$overlay]=true
        msgs+=( " + $overlay\n" )
        # Copy overla resources to bundles dir (if exists)
        resource_path=$MOD_PATH/resources/${overlay%%.*}
        if [ -d "$resource_path" ]; then
            mkdir -p $bundles_dir/resources
            cp -r $resource_path $bundles_dir/resources
            # add absolute path for resources
            render_resources_path $bundles_dir/o/$overlay
        fi
    done
    ((${#overlay_opts[@]})) && overlay_opts+=("")  # right padding

    echo "Created $target ${app_release_name}bundle and overlays ($msg):"
    echo -e " ${msgs[@]}"
else
    echo -e "Created $target ${app_release_name}bundle ($msg)\n"
fi

base_bundle=$bundles_dir/`basename $bundle`
echo -e "juju deploy${JUJU_DEPLOY_OPTS} ${base_bundle}${overlay_opts[@]:- }${channel_param}\n " > ${bundles_dir}/command
finish
