#!/bin/bash
# This file contains ubuntu series names along with their openstack
# counterpart release names. Each stable release of Ubuntu has a
# contemporaneous release of Openstack shipped in its main archives. Each LTS
# release of Ubuntu has the ability to install Openstack releases from between
# LTS releases by using the Ubuntu Cloud Archive. Each cloud archive release
# corresponds back to a release avaiable in a stable release of Ubuntu.
#
# More info on releases at https://ubuntu.com/about/release-cycle

# TODO: keep this list up-to-date with supported series in order have a way to
#       know when release names wrap around the alphabet.
declare -A lts_order=( [0]=trusty
                       [1]=xenial
                       [2]=bionic
                       [3]=focal
                       [4]=jammy
)
declare -A lts=( [trusty]=icehouse
                 [xenial]=mitaka
                 [bionic]=queens
                 [focal]=ussuri
                 [jammy]=yoga
)
declare -A nonlts=( [hirsute]=wallaby
                    [impish]=xena
                    [kinetic]=zed
)

# Reverse lookups (revision to series)
declare -A lts_rev=()
for s in ${!lts[@]}; do
    lts_rev[${lts[$s]}]=$s
done
declare -A nonlts_rev=()
for s in ${!nonlts[@]}; do
    nonlts_rev[${nonlts[$s]}]=$s
done

# Alphabetically sorted arrays of release names
readarray -t lts_releases_sorted<<<\
"`echo -n ${lts[@]}| tr ' ' '\n' | sort -r`"
readarray -t nonlts_releases_sorted<<<\
"`echo -n ${nonlts[@]}| tr ' ' '\n' | sort -r`"
readarray -t all_releases_sorted<<<"\
`{ echo -n ${lts[@]}; echo " ${nonlts[@]}"; }| tr ' ' '\n'| sort -r`"
