name: Linter
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt install --no-install-recommends --yes \
            python3-bashate \
            shellcheck
      - name: Get sources
        uses: actions/checkout@v3
      - name: Lint bash scripts
        run: make lint

  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Commit Message
        run: |
          ./tools/lint-git-messages.sh \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }}
